### PR TITLE
New Interfaces implemented, refactoring done, so it might seem alot, …

### PR DESCRIPTION
**Pull request by calliminator**
…but it is just that a lot of classes, that had a connection, now have a connection to the interface instead

### CODE REVIEW

**Comment by GloeStoe** [comment]
looks good to me

**Review by GloeStoe — APPROVED** [review]
.

**Comment by LuposX** [comment]
You forgot all the typehints for the return values @calliminator

**Comment by calliminator** [comment]
> You forgot all the typehints for the return values @calliminator

typehints for return values have been added

**Pull request merged**
